server {
listen 80;
server_name localhost;

root /usr/share/nginx/html;
index index.html;

location / {
    # Crucial for React Router (SPA): If a file isn't found (like /admin),
    # serve index.html and let React handle the path.
    try_files $uri $uri/ /index.html;
}

# Optional: Cache control for static assets
location ~* \.(?:css|js|map|jpe?g|gif|png)$ {
    expires 1y;
    add_header Cache-Control "public";
}

proxy_buffering off;


}