spring.application.name=notification-service

###############################################
### DATABASE CONNECTIVITY CONFIGURATIONS ###
###############################################
database.ip=${NOTIFICATION_DB_IP:localhost}
database.port=${NOTIFICATION_DB_PORT:6006}
database.user=${POSTGRES_USER:postgres}
database.password=${POSTGRES_PASSWORD:222819}
database.name=${NOTIFICATION_DB:notification_db}

spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://${database.ip}:${database.port}/${database.name}
spring.datasource.username=${database.user}
spring.datasource.password=${database.password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

###############################################
### RABBITMQ CONFIGURATIONS ###
###############################################
spring.rabbitmq.host=${BROKER_HOST:localhost}
spring.rabbitmq.port=${BROKER_PORT:6672}
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

###############################################
### JWT CONFIGURATIONS ###
###############################################
jwt.secret=${JWT_SECRET:super-secret-demo-key-change-me!}

###############################################
### EMBEDDED TOMCAT CONFIGURATIONS ###
###############################################
server.port=${PORT:8085}
server.address=0.0.0.0
