name: merkador # This locks the prefix for all services, making it easier to identify them in Docker commands and ensuring consistent naming across environments.

services:

  traefik:
    image: traefik:v3.6.2
    container_name: traefik
    command:
      - "--api.insecure=true"              # Dev dashboard enabled on :8080
      - "--providers.docker=true"          # Detect Docker containers automatically
      - "--entrypoints.web.address=:80"    # Single HTTP entrypoint
    ports:
      - "80:80"                            # Access APIs via Traefik
      - "8080:8080"                        # Dev dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - docker_network
    restart: unless-stopped
    labels:
       # 1) Middleware to strip /api prefix
      - "traefik.http.middlewares.strip-api.stripprefix.prefixes=/api"

      # 3) Middleware: CORS for frontend dev server
      - "traefik.http.middlewares.cors-frontend.headers.accesscontrolalloworiginlist=http://localhost:5173"
      - "traefik.http.middlewares.cors-frontend.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.cors-frontend.headers.accesscontrolallowheaders=Authorization,Content-Type"
      - "traefik.http.middlewares.cors-frontend.headers.accesscontrolallowcredentials=true"

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "6672:5672"   
      - "16672:15672" # Management Dashboard
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - docker_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-cart:
    image: redis:7
    container_name: redis-cart
    ports:
      - "6379:6379"
    networks:
      - docker_network

  frontend-app:
    build: 
      context: ./frontend_app
    container_name: frontend-app
    networks:
      - docker_network
    restart: unless-stopped
    labels:
      - "traefik.enable=true" # <--- DISABLING/ENABLING THIS CONTAINER FOR LOCAL/CONTAINERIZED FRONTEND | SET TO 'true' FOR PRODUCTION
      
      # Catch all root path requests (/) except /api and route to frontend
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`) && !PathPrefix(`/api`)"
      - "traefik.http.routers.frontend.service=frontend-service"
      - "traefik.http.routers.frontend.entrypoints=web" 
      - "traefik.http.services.frontend-service.loadbalancer.server.port=80" # Nginx default port  
  
  user-ms:
    build: ./user_ms
    container_name: user-ms
    volumes:
      - ./upload_data:/upload_data # Mount local directory for user uploads (like avatars)
    ports:
      - "8082:8082" # Optional for direct testing
    environment:
      - DB_IP=${USER_DB_IP}
      - DB_PORT=${USER_DB_PORT}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DBNAME=${USER_DB}
      - BROKER_HOST=${BROKER_HOST}
      - BROKER_PORT=${BROKER_PORT}
    depends_on:
      rabbitmq:
        condition: service_healthy
      user-db:
        condition: service_started
    networks:
      - docker_network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"

      # --- Public routes (no JWT) ---
      - "traefik.http.routers.user-public.rule=PathPrefix(`/api/users/uploads`)"
      - "traefik.http.routers.user-public.service=user"
      - "traefik.http.routers.user-public.middlewares=strip-api, cors-frontend"
      - "traefik.http.routers.user-public.priority=100"

      # --- Protected routes (JWT required) ---
      - "traefik.http.routers.user-secure.rule=PathPrefix(`/api/users`)"
      - "traefik.http.routers.user-secure.service=user"
      - "traefik.http.routers.user-secure.middlewares=strip-api, cors-frontend, forward-auth" # we use Traefik's built-in forward auth middleware which will call our JWT validation endpoint
      - "traefik.http.routers.user-secure.entrypoints=web"


      - "traefik.http.services.user.loadbalancer.server.port=8082"

  credential-ms:
    build: ./credentials_ms
    container_name: credential-ms
    ports:
      - "8081:8081"
    environment:
      - DB_IP=${CREDENTIAL_DB_IP}
      - DB_PORT=${CREDENTIAL_DB_PORT}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DBNAME=${CREDENTIAL_DB}
      - BROKER_HOST=${BROKER_HOST}
      - BROKER_PORT=${BROKER_PORT}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      rabbitmq:
          condition: service_healthy
      credential-db:
        condition: service_started
      user-ms:
        condition: service_started
    networks:
      - docker_network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"

      # Declare the forward auth middleware that will be used by both user-ms and credential-ms for protected routes. This will call our /credentials/validate endpoint to check JWT validity.
      - "traefik.http.middlewares.forward-auth.forwardauth.address=http://credential-ms:8081/credentials/validate"
      - "traefik.http.middlewares.forward-auth.forwardauth.trustForwardHeader=true"

      # --- Public routes (no JWT) ---
      - "traefik.http.routers.credential-public.rule=PathPrefix(`/api/credentials/login`) || PathPrefix(`/api/credentials/add`) || PathPrefix(`/api/credentials/activate`) || PathPrefix(`/api/credentials/resend-code`) || PathPrefix(`/api/credentials/forgot-password`) || PathPrefix(`/api/credentials/reset-password`) || PathPrefix(`/api/credentials/reactivate-account`)"
      - "traefik.http.routers.credential-public.service=credential"
      - "traefik.http.routers.credential-public.middlewares=strip-api, cors-frontend"
      - "traefik.http.routers.credential-public.entrypoints=web"

      # --- Protected routes (JWT required) ---
      - "traefik.http.routers.credential-secure.rule=PathPrefix(`/api/credentials`)"
      - "traefik.http.routers.credential-secure.service=credential"
      - "traefik.http.routers.credential-secure.middlewares=strip-api, cors-frontend, forward-auth"
      - "traefik.http.routers.credential-secure.entrypoints=web"

      # Set higher priority for public routes to ensure they are matched before the catch-all secure route. This allows login and registration to work without JWT, while all other credential routes require authentication.
      - "traefik.http.routers.credential-public.priority=100" 
      - "traefik.http.routers.credential-secure.priority=50"

      - "traefik.http.services.credential.loadbalancer.server.port=8081"

  order-ms:
    build: ./order-service
    container_name: order-ms
    ports:
      - "8083:8083" # Optional for direct testing
    environment:
      - ORDER_DB_IP=order-db
      - ORDER_DB_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ORDER_DB=${ORDER_DB}
      - REDIS_HOST=redis-cart
      - REDIS_PORT=6379
      - BROKER_HOST=rabbitmq
      - BROKER_PORT=5672
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      rabbitmq:
        condition: service_healthy
      order-db:
        condition: service_started
      redis-cart:
        condition: service_started
    networks:
      - docker_network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.order-ms.rule=(Path(`/api/orders`) || PathPrefix(`/api/orders/`) || Path(`/api/cart`) || PathPrefix(`/api/cart/`) || PathPrefix(`/api/admin/orders`))"
      - "traefik.http.routers.order-ms.service=order-ms"
      - "traefik.http.routers.order-ms.middlewares=strip-api, cors-frontend, forward-auth"
      - "traefik.http.routers.order-ms.entrypoints=web"
      - "traefik.http.services.order-ms.loadbalancer.server.port=8083"

  product-ms:
    build: ./product-service
    container_name: product-ms
    ports:
      - "8084:8084"
    environment:
      - DB_IP=product-db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DBNAME=${PRODUCT_DB}
      - BROKER_HOST=${BROKER_HOST}
      - BROKER_PORT=${BROKER_PORT}
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASS=${RABBITMQ_DEFAULT_PASS}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      rabbitmq:
        condition: service_healthy
      product-db:
        condition: service_started
    networks:
      - docker_network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"

      # --- Public routes GET (fara JWT) ---
      - "traefik.http.routers.product-public.rule=(PathPrefix(`/api/products`) || PathPrefix(`/api/categories`) || PathPrefix(`/api/uploads/products`)) && Method(`GET`)"
      - "traefik.http.routers.product-public.service=product-ms"
      - "traefik.http.routers.product-public.middlewares=strip-api,cors-frontend"
      - "traefik.http.routers.product-public.entrypoints=web"
      - "traefik.http.routers.product-public.priority=10"

      # --- Protected routes (JWT required) ---
      - "traefik.http.routers.product-secure.rule=PathPrefix(`/api/products`) || PathPrefix(`/api/categories`) || PathPrefix(`/api/uploads/products`)"
      - "traefik.http.routers.product-secure.service=product-ms"
      - "traefik.http.routers.product-secure.middlewares=strip-api,cors-frontend,forward-auth"
      - "traefik.http.routers.product-secure.entrypoints=web"
      - "traefik.http.routers.product-secure.priority=5"

      - "traefik.http.services.product-ms.loadbalancer.server.port=8084"
  post-ms:
    build: ./post-service
    container_name: post-ms
    ports:
      - "8086:8086"
    environment:
      - POST_DB_IP=post-db
      - POST_DB_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POST_DB=${POST_DB}
      - BROKER_HOST=rabbitmq
      - BROKER_PORT=5672
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      rabbitmq:
        condition: service_healthy
      post-db:
        condition: service_started
    networks:
      - docker_network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.post-ms.rule=PathPrefix(`/api/reviews`)"
      - "traefik.http.routers.post-ms.service=post-ms"
      - "traefik.http.routers.post-ms.middlewares=strip-api, cors-frontend, forward-auth"
      - "traefik.http.routers.post-ms.entrypoints=web"
      - "traefik.http.services.post-ms.loadbalancer.server.port=8086"

  # --- Databases ---
  user-db:
    image: postgres:16
    container_name: user-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${USER_DB}
    ports:
      - "6001:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - docker_network

  credential-db:
    image: postgres:16
    container_name: credential-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${CREDENTIAL_DB}
    ports:
      - "6002:5432"
    volumes:
      - credential_db_data:/var/lib/postgresql/data
    networks:
      - docker_network
      
  order-db:
    image: postgres:16
    container_name: order-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${ORDER_DB}
    ports:
      - "6003:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
    networks:
      - docker_network

  product-db:
    image: postgres:16
    container_name: product-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${PRODUCT_DB}
    ports:
      - "6004:5432"
    volumes:
      - product_db_data:/var/lib/postgresql/data
    networks:
      - docker_network

  post-db:
    image: postgres:16
    container_name: post-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POST_DB}
    ports:
      - "6005:5432"
    volumes:
      - post_db_data:/var/lib/postgresql/data
    networks:
      - docker_network
  
volumes:
  user_db_data:
  credential_db_data:
  order_db_data:
  product_db_data:
  post_db_data:

networks:
  docker_network:
    driver: bridge
