spring.application.name=Credential_Management_MS


###############################################
### DATABASE CONNECTIVITY CONFIGURATIONS ###
###############################################
database.ip = ${DB_IP:localhost}
database.port = ${DB_PORT:5432}
database.user = ${DB_USER:postgres}
database.password = ${DB_PASSWORD:222819}
database.name = ${DB_DBNAME:credential_db}

spring.sql.init.platform=postgres
spring.datasource.url = jdbc:postgresql://${database.ip}:${database.port}/${database.name}
spring.datasource.username = ${database.user}
spring.datasource.password = ${database.password}

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.show_sql=true
server.tomcat.threads.max = 1
###############################################
### LOGGING CONFIGURATIONS ###
###############################################
logging.level.root=warn
logging.level.org.springframework=warn
###############################################
### EMBEDDED TOMCAT CONFIGURATIONS ###
###############################################
server.port=${PORT:8081}
server.address=0.0.0.0
###############################################
### RABBITMQ CONFIGURATIONS ###
###############################################
spring.rabbitmq.host=${BROKER_HOST:localhost}
spring.rabbitmq.port=${BROKER_PORT:6672}
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

#DISABLE SPRINGBOOT SECURITY // already done in the filter chain
#spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.servlet.SecurityAutoConfiguration

