spring.application.name=order-service

###############################################
### DATABASE CONNECTIVITY CONFIGURATIONS ###
###############################################
database.ip = ${ORDER_DB_IP:localhost}
database.port = ${ORDER_DB_PORT:6003}
database.user = ${POSTGRES_USER:postgres}
database.password = ${POSTGRES_PASSWORD:222819}
database.name = ${ORDER_DB:order_service_db}

spring.sql.init.platform=postgres
spring.datasource.url = jdbc:postgresql://${database.ip}:${database.port}/${database.name}
spring.datasource.username = ${database.user}
spring.datasource.password = ${database.password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

###############################################
### REDIS CONFIGURATIONS ###
###############################################
redis.host=${REDIS_HOST:localhost}
redis.port=${REDIS_PORT:6379}

spring.data.redis.host=${redis.host}
spring.data.redis.port=${redis.port}

###############################################
### RABBITMQ CONFIGURATIONS ###
###############################################
spring.rabbitmq.host=${BROKER_HOST:localhost}
spring.rabbitmq.port=${BROKER_PORT:6672}
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

###############################################
### JWT CONFIGURATIONS ###
###############################################
jwt.secret=${JWT_SECRET}

###############################################
### EMBEDDED TOMCAT CONFIGURATIONS ###
###############################################
server.port=${PORT:8083}
server.address=0.0.0.0
