server.port=8084
spring.application.name=order-service

# Configurare conexiune baza de date
spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=parola_ta
